### ISSUE TITLE
unexpect {{end}} in service.yml

### ISSUE THREAD

**Issue by Pancongwen** [varyumin/netdata#1]
## action
```
$ git clone https://github.com/varyumin/netdata.git
$ cd netdata/
$ helm install --name netdata .
```
## output
```
Error: parse error in "netdata/templates/service.yaml": template: netdata/templates/service.yaml:13: unexpected {{end}}
```

## version
```
$ git log -n 1
commit ba5858b665831cfc4755aadbe765d1124f24b0a0 (HEAD -> master, origin/master, origin/HEAD)
Merge: 2165c45 f2c18a5
Author: Ryumin Vladimir Aleksandrovich (Devops) <v.a.ryumin@tinkoff.ru>
Date:   Mon Mar 11 16:08:09 2019 +0300

    Added dynamic annotations from service

$ helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
```

## expect
no error

## extra
After I remove the line 13 in `templates/service.yaml`, the installation seems work.
```yaml
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "netdata.name" . }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: master
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and ( eq .Values.service.type  "NodePort" ) ( .Values.service.nodePort ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    app: {{ template "netdata.name" . }}
    release: {{ .Release.Name }}
    role: master
```
I'm new to helm chart, and i don't know why.
